routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::post('/createPost', 'PostController@store')->name('post.create');
Route::resource('posts', 'PostController');
Route::get('change-like/{id}','PostController@changeLike');

app/Like.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Like extends Model
{


    public function user(){
        return $this->belongsTo('App\User');
    }
    public function post(){
        return $this->belongsTo('App\Post');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    private $body;

    public function user(){
        return $this->belongsTo('App\User');
    }
    public function likes(){
        return $this->hasOne('App\Like');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){
        return $this->hasMany('App\Post');
    }
    public function likes(){
        return $this->belongsTo('App\Like');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HomeController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $posts = Post::all();
        return view('home')->with('posts', $posts);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Post;
use App\Like;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'body' => 'required|max:1000'
        ]);
        $post = new Post();
        $post->body = $request['body'];
        if($request->user()->posts()->save($post)){
            $notification = [
                'message' => 'Post Added Successfully!',
                'alert-type' => 'success'
            ];
        } else {
            $notification = [
                'message' => 'Post Adding Failed!',
                'alert-type' => 'error'
            ];
        }


        return back()->with($notification);
    }


    public function edit($id)
    {
        $posts = POST::where('id' ,$id)->first();
        return view('editPost')->with('posts', $posts);
    }

    public function update(Request $request, $id)
    {
        $post = POST::find($id);

        $post->body = $request->body;

        $result = $post->save();
        if($result){
            $notification = [
                'message' => 'Post edited Successfully!',
                'alert-type' => 'success'
            ];
        } else {
            $notification = [
                'message' => 'Post edit Failed!',
                'alert-type' => 'error'
            ];
        }

        return redirect('home')->with($notification);
    }

    public function changeLike($id){
        $user = Auth::user()->id;
       $makeLike = Like::where([
            'user_id' => $user,
            'post_id' => $id
        ])->first();
//       return $makeLike;
       if ($makeLike){
           $un = $makeLike->like == 0 ? 1 : 0;
           Like::where([
               'user_id' => Auth::user()->id,
               'post_id' => $id
           ])->update([
                   'like' => $un
               ]);
           return response()->json(['status' => $un, 'message' => 'Like Changed']);
       } else {
           Like::insert([
               'user_id' => $user,
               'post_id' => $id,
               'like' => 1
           ]);
           return response()->json(['message' => 'Like done']);
       }
    }

    public function destroy($id)
    {
        $delete = POST::find($id)->delete();
        if($delete){
            $notification = [
                'message' => 'Post Deleted Successfully!',
                'alert-type' => 'success'
            ];
        } else {
                $notification = [
                    'message' => 'Post Delete Failed!',
                    'alert-type' => 'error'
                ];
            }

        return back()->with($notification);
    }
}

resources/views/editPost.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('posts.update', $posts->id) }}" class="form-group" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <textarea name="body" id="" rows="5" class="form-control border
                            border-success">{{ $posts->body }}</textarea>
                            <input type="submit" value="Submit" class="mt-2 form-control btn btn-lg btn-success">
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                        <form action="{{ route('posts.store') }}" class="form-group" method="post">
                            @csrf
                            <textarea name="body" id="" rows="5" class="form-control border border-success"></textarea>
                            <input type="submit" value="Submit" class="mt-2 form-control btn btn-lg btn-success">
                        </form>
                </div>
                <hr>
                <div class="card-body">
                    @foreach($posts as $post)
                    <p>Posted by <strong>{{ $post->user->name }}</strong> on {{ $post->created_at }}</p>
                    <p> {{ $post->body }} </p>
                    <hr>
                    <p> <form action="/posts/{{ $post->id }}" method="post" > @csrf
                            <a href="change-like/{{$post->id}}" class="btn btn-success like">
                                @if($post->likes)
                                    @if($post->likes->like == 0)
                                        Like
                                    @elseif($post->likes->like == 1)
                                        Unlike
                                    @endif
                                    @else Unlike
                                @endif

                            </a>
                        @if(Auth::user() == $post->user)

                                || <button formaction="/posts/{{ $post->id
                    }}/edit" type="submit" name="_method" value="GET" class="btn
                    btn-warning">Edit</button> || <button type="submit" name="_method" value="DELETE" class="btn
                            btn-danger"/>Delete</button>

                        @endif
                        </form>
                        <hr>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/toastr.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/toastr.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script>
      @if(Session::has('message'))
        let type = "{{Session::get('alert-type','info')}}";
        switch(type){
            case 'success':
                toastr.success("{{ Session::get('message') }}", "Success", {
                    closeButton: true,
                    newestOnTop: true,
                    progressBar: true,
                    positionClass: "toast-top-center",
                    showDuration: "300",
                    hideDuration: "1000",
                    timeOut: "5000",
                    extendedTimeOut: "1000",
                    showEasing: "swing",
                    hideEasing: "linear",
                    showMethod: "fadeIn",
                    hideMethod: "fadeOut"});
                break;
            case 'error':
                toastr.error("{{ Session::get('message') }}", "Error", {
                    closeButton: true,
                    newestOnTop: true,
                    progressBar: true,
                    positionClass: "toast-top-center",
                    showDuration: "300",
                    hideDuration: "1000",
                    timeOut: "5000",
                    extendedTimeOut: "1000",
                    showEasing: "swing",
                    hideEasing: "linear",
                    showMethod: "fadeIn",
                    hideMethod: "fadeOut"});
                break;
        }
        @endif
        @if ($errors->any())
          @foreach ($errors->all() as $error)
            toastr.warning("{{ $error }}", "Error", {
            closeButton: true,
            newestOnTop: true,
            progressBar: true,
            positionClass: "toast-top-center",
            showDuration: "300",
            hideDuration: "1000",
            timeOut: "5000",
            extendedTimeOut: "1000",
            showEasing: "swing",
            hideEasing: "linear",
            showMethod: "fadeIn",
            hideMethod: "fadeOut"});
          @endforeach
        @endif
    </script>

</body>
</html>